dist: xenial
language: python
install:
- pip install --upgrade pip wheel setuptools
- pip install tox coveralls
script:
- tox
matrix:
  include:
  - python: '3.7'
    env: TOXENV=py37-django2.2
  - python: '3.7'
    env: TOXENV=py37-django3.0

  - python: '3.8'
    env: TOXENV=py38-django2.2
  - python: '3.8'
    env: TOXENV=py38-django3.0
