name: NPM

on:
   push:
     tags:
       - 'v*'

jobs:
  publish:
    name: Build and publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm run prepackage
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - run: npm run postpackage
